import type { InputField } from './curlParser';

export interface BuiltinVideoModel {
  id: string;
  name: string;
  model_id: string;
  category: string;
  endpoint: string;
  method: string;
  default_input: Record<string, unknown>;
  input_schema: InputField[];
  has_prompt: boolean;
  has_image_input: boolean;
  has_callback: boolean;
  is_active: true;
  is_builtin: true;
  badge?: string;
}

const ENDPOINT = '/api/v1/jobs/createTask';

export const BUILTIN_VIDEO_MODELS: BuiltinVideoModel[] = [
  {
    id: 'builtin-veo3-t2v',
    name: 'Veo 3.0 (Text to Video)',
    model_id: 'veo3/text-to-video',
    category: 'text-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: false,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Google',
    default_input: { model: 'veo3/text-to-video', input: { prompt: '', aspect_ratio: '16:9', resolution: '720p' } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: true, label: 'Prompt' },
      { key: 'aspect_ratio', path: 'input.aspect_ratio', type: 'string', value: '16:9', required: false, label: 'Aspect Ratio' },
      { key: 'resolution', path: 'input.resolution', type: 'string', value: '720p', required: false, label: 'Resolution' },
    ],
  },
  {
    id: 'builtin-veo31-i2v',
    name: 'Veo 3.1 (Image to Video)',
    model_id: 'veo/3.1-image-to-video',
    category: 'image-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: true,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Google',
    default_input: { model: 'veo/3.1-image-to-video', input: { prompt: '', aspect_ratio: '16:9', duration: '8' } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: true, label: 'Prompt' },
      { key: 'aspect_ratio', path: 'input.aspect_ratio', type: 'string', value: '16:9', required: false, label: 'Aspect Ratio' },
      { key: 'duration', path: 'input.duration', type: 'string', value: '8', required: false, label: 'Duration (s)' },
    ],
  },
  {
    id: 'builtin-kling3-t2v',
    name: 'Kling 3.0 (Text to Video)',
    model_id: 'kling-3.0/video',
    category: 'text-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: false,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Kling',
    default_input: { model: 'kling-3.0/video', input: { prompt: '', mode: 'pro', duration: '5', aspect_ratio: '16:9' } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: true, label: 'Prompt' },
      { key: 'mode', path: 'input.mode', type: 'string', value: 'pro', required: false, label: 'Mode (std/pro)' },
      { key: 'duration', path: 'input.duration', type: 'string', value: '5', required: false, label: 'Duration (s)' },
      { key: 'aspect_ratio', path: 'input.aspect_ratio', type: 'string', value: '16:9', required: false, label: 'Aspect Ratio' },
    ],
  },
  {
    id: 'builtin-kling3-i2v',
    name: 'Kling 3.0 (Image to Video)',
    model_id: 'kling-3.0/video',
    category: 'image-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: true,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Kling',
    default_input: { model: 'kling-3.0/video', input: { image_urls: [], prompt: '', mode: 'pro', duration: '5', aspect_ratio: '16:9' } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: false, label: 'Prompt' },
      { key: 'mode', path: 'input.mode', type: 'string', value: 'pro', required: false, label: 'Mode (std/pro)' },
      { key: 'duration', path: 'input.duration', type: 'string', value: '5', required: false, label: 'Duration (s)' },
      { key: 'aspect_ratio', path: 'input.aspect_ratio', type: 'string', value: '16:9', required: false, label: 'Aspect Ratio' },
    ],
  },
  {
    id: 'builtin-kling21-i2v',
    name: 'Kling 2.1 (Image to Video)',
    model_id: 'kling/v2.1-image-to-video',
    category: 'image-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: true,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Kling',
    default_input: { model: 'kling/v2.1-image-to-video', input: { prompt: '', mode: 'pro', duration: '5', aspect_ratio: '16:9' } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: false, label: 'Prompt' },
      { key: 'mode', path: 'input.mode', type: 'string', value: 'pro', required: false, label: 'Mode (std/pro)' },
      { key: 'duration', path: 'input.duration', type: 'string', value: '5', required: false, label: 'Duration (s)' },
      { key: 'aspect_ratio', path: 'input.aspect_ratio', type: 'string', value: '16:9', required: false, label: 'Aspect Ratio' },
    ],
  },
  {
    id: 'builtin-kling21-v2v',
    name: 'Kling 2.1 (Video to Video)',
    model_id: 'kling/v2.1-video-to-video',
    category: 'video-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: false,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Kling',
    default_input: { model: 'kling/v2.1-video-to-video', input: { prompt: '', mode: 'pro', duration: '5' } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: false, label: 'Prompt' },
      { key: 'mode', path: 'input.mode', type: 'string', value: 'pro', required: false, label: 'Mode (std/pro)' },
      { key: 'duration', path: 'input.duration', type: 'string', value: '5', required: false, label: 'Duration (s)' },
    ],
  },
  {
    id: 'builtin-wan22-t2v-turbo',
    name: 'Wan 2.2 Turbo (Text to Video)',
    model_id: 'wan/2-2-a14b-text-to-video-turbo',
    category: 'text-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: false,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Wan',
    default_input: { model: 'wan/2-2-a14b-text-to-video-turbo', input: { prompt: '', resolution: '720p', enable_prompt_expansion: false, seed: 0, acceleration: 'none' } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: true, label: 'Prompt' },
      { key: 'resolution', path: 'input.resolution', type: 'string', value: '720p', required: false, label: 'Resolution' },
      { key: 'enable_prompt_expansion', path: 'input.enable_prompt_expansion', type: 'boolean', value: false, required: false, label: 'Prompt Expansion' },
      { key: 'seed', path: 'input.seed', type: 'number', value: 0, required: false, label: 'Seed' },
      { key: 'acceleration', path: 'input.acceleration', type: 'string', value: 'none', required: false, label: 'Acceleration' },
    ],
  },
  {
    id: 'builtin-wan22-i2v-turbo',
    name: 'Wan 2.2 Turbo (Image to Video)',
    model_id: 'wan/2-2-a14b-image-to-video-turbo',
    category: 'image-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: true,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Wan',
    default_input: { model: 'wan/2-2-a14b-image-to-video-turbo', input: { prompt: '', resolution: '720p', enable_prompt_expansion: false, seed: 0, acceleration: 'none' } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: true, label: 'Prompt' },
      { key: 'resolution', path: 'input.resolution', type: 'string', value: '720p', required: false, label: 'Resolution' },
      { key: 'enable_prompt_expansion', path: 'input.enable_prompt_expansion', type: 'boolean', value: false, required: false, label: 'Prompt Expansion' },
      { key: 'seed', path: 'input.seed', type: 'number', value: 0, required: false, label: 'Seed' },
      { key: 'acceleration', path: 'input.acceleration', type: 'string', value: 'none', required: false, label: 'Acceleration' },
    ],
  },
  {
    id: 'builtin-wan22-t2v',
    name: 'Wan 2.2 (Text to Video)',
    model_id: 'wan/2-2-a14b-text-to-video',
    category: 'text-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: false,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Wan',
    default_input: { model: 'wan/2-2-a14b-text-to-video', input: { prompt: '', resolution: '720p', enable_prompt_expansion: false, seed: 0 } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: true, label: 'Prompt' },
      { key: 'resolution', path: 'input.resolution', type: 'string', value: '720p', required: false, label: 'Resolution' },
      { key: 'enable_prompt_expansion', path: 'input.enable_prompt_expansion', type: 'boolean', value: false, required: false, label: 'Prompt Expansion' },
      { key: 'seed', path: 'input.seed', type: 'number', value: 0, required: false, label: 'Seed' },
    ],
  },
  {
    id: 'builtin-wan22-i2v',
    name: 'Wan 2.2 (Image to Video)',
    model_id: 'wan/2-2-a14b-image-to-video',
    category: 'image-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: true,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Wan',
    default_input: { model: 'wan/2-2-a14b-image-to-video', input: { prompt: '', resolution: '720p', enable_prompt_expansion: false, seed: 0 } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: true, label: 'Prompt' },
      { key: 'resolution', path: 'input.resolution', type: 'string', value: '720p', required: false, label: 'Resolution' },
      { key: 'enable_prompt_expansion', path: 'input.enable_prompt_expansion', type: 'boolean', value: false, required: false, label: 'Prompt Expansion' },
      { key: 'seed', path: 'input.seed', type: 'number', value: 0, required: false, label: 'Seed' },
    ],
  },
  {
    id: 'builtin-hailuo-t2v',
    name: 'Hailuo (Text to Video)',
    model_id: 'hailuo/text-to-video',
    category: 'text-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: false,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Hailuo',
    default_input: { model: 'hailuo/text-to-video', input: { prompt: '', duration: '6' } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: true, label: 'Prompt' },
      { key: 'duration', path: 'input.duration', type: 'string', value: '6', required: false, label: 'Duration (s)' },
    ],
  },
  {
    id: 'builtin-hailuo-i2v',
    name: 'Hailuo (Image to Video)',
    model_id: 'hailuo/image-to-video',
    category: 'image-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: true,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Hailuo',
    default_input: { model: 'hailuo/image-to-video', input: { prompt: '', duration: '6' } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: false, label: 'Prompt' },
      { key: 'duration', path: 'input.duration', type: 'string', value: '6', required: false, label: 'Duration (s)' },
    ],
  },
  {
    id: 'builtin-luma-t2v',
    name: 'Luma Dream Machine (Text to Video)',
    model_id: 'luma/dream-machine-text-to-video',
    category: 'text-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: false,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Luma',
    default_input: { model: 'luma/dream-machine-text-to-video', input: { prompt: '', duration: '5', aspect_ratio: '16:9' } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: true, label: 'Prompt' },
      { key: 'duration', path: 'input.duration', type: 'string', value: '5', required: false, label: 'Duration (s)' },
      { key: 'aspect_ratio', path: 'input.aspect_ratio', type: 'string', value: '16:9', required: false, label: 'Aspect Ratio' },
    ],
  },
  {
    id: 'builtin-luma-i2v',
    name: 'Luma Dream Machine (Image to Video)',
    model_id: 'luma/dream-machine-image-to-video',
    category: 'image-to-video',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: true,
    has_image_input: true,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Luma',
    default_input: { model: 'luma/dream-machine-image-to-video', input: { prompt: '', duration: '5', aspect_ratio: '16:9' } },
    input_schema: [
      { key: 'prompt', path: 'input.prompt', type: 'string', value: '', required: false, label: 'Prompt' },
      { key: 'duration', path: 'input.duration', type: 'string', value: '5', required: false, label: 'Duration (s)' },
      { key: 'aspect_ratio', path: 'input.aspect_ratio', type: 'string', value: '16:9', required: false, label: 'Aspect Ratio' },
    ],
  },
  {
    id: 'builtin-kling-lipsync',
    name: 'Kling Lip Sync',
    model_id: 'kling/lip-sync',
    category: 'lip-sync',
    endpoint: ENDPOINT,
    method: 'POST',
    has_prompt: false,
    has_image_input: true,
    has_callback: false,
    is_active: true,
    is_builtin: true,
    badge: 'Kling',
    default_input: { model: 'kling/lip-sync', input: { mode: 'audio2video' } },
    input_schema: [
      { key: 'mode', path: 'input.mode', type: 'string', value: 'audio2video', required: false, label: 'Mode' },
    ],
  },
];

export function getBuiltinModelsForCategory(category: string): BuiltinVideoModel[] {
  return BUILTIN_VIDEO_MODELS.filter((m) => m.category === category);
}
