import { useState } from 'react';
import { Target, Lightbulb, DollarSign, MessageSquare, Swords, FileText, BarChart3, AlertTriangle } from 'lucide-react';
import type { AnalysisResult, ROIResult, OutreachResult, CompetitorResult, ProposalResult } from '../../../lib/ai/types';
import BusinessIntelligenceTab from './tabs/BusinessIntelligenceTab';
import ServiceRecommendationsTab from './tabs/ServiceRecommendationsTab';
import ROICalculatorTab from './tabs/ROICalculatorTab';
import OutreachTab from './tabs/OutreachTab';
import CompetitorTab from './tabs/CompetitorTab';
import ProposalTab from './tabs/ProposalTab';
import FullReportTab from './tabs/FullReportTab';

interface Props {
  analysis: AnalysisResult | null;
  roi: ROIResult | null;
  outreach: OutreachResult | null;
  competitor: CompetitorResult | null;
  proposal: ProposalResult | null;
  businessName: string;
  currentStep: number;
  totalTokens: number;
  modelsUsed?: Record<string, string>;
}

const TABS = [
  { id: 'intelligence', label: 'Intelligence', icon: Target, step: 1, taskKey: 'business_analysis' },
  { id: 'recommendations', label: 'Services', icon: Lightbulb, step: 1, taskKey: 'business_analysis' },
  { id: 'roi', label: 'ROI', icon: DollarSign, step: 2, taskKey: 'roi_calculation' },
  { id: 'outreach', label: 'Outreach', icon: MessageSquare, step: 3, taskKey: 'cold_messages' },
  { id: 'competitor', label: 'Competitor', icon: Swords, step: 4, taskKey: 'competitor_analysis' },
  { id: 'proposal', label: 'Proposal', icon: FileText, step: 5, taskKey: 'proposal_writing' },
  { id: 'report', label: 'Full Report', icon: BarChart3, step: 5, taskKey: '' },
];

function ModelBadge({ modelId }: { modelId?: string }) {
  if (!modelId) return null;

  const name = modelId.includes('/') ? modelId.split('/').pop() : modelId;

  return (
    <span className="inline-flex items-center gap-1 text-[10px] text-gray-500 bg-dark-800 border border-white/5 px-2 py-0.5 rounded-full">
      Generated by {name}
    </span>
  );
}

function TabError({ label }: { label: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      <AlertTriangle className="w-10 h-10 text-yellow-400 mb-3" />
      <h3 className="text-sm font-semibold text-gray-300 mb-1">{label} generation failed</h3>
      <p className="text-xs text-gray-500 max-w-sm">The AI response was incomplete or could not be parsed. Try running the analysis again.</p>
    </div>
  );
}

export default function AIResultsDashboard({ analysis, roi, outreach, competitor, proposal, businessName, currentStep, totalTokens, modelsUsed = {} }: Props) {
  const [activeTab, setActiveTab] = useState('intelligence');

  const estimatedCost = (totalTokens / 1000) * 0.003;
  const activeTabConfig = TABS.find((t) => t.id === activeTab);
  const activeModel = activeTabConfig?.taskKey ? modelsUsed[activeTabConfig.taskKey] : undefined;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2 overflow-x-auto pb-1 scrollbar-thin">
          {TABS.map((tab) => {
            const available = currentStep >= tab.step;
            return (
              <button
                key={tab.id}
                onClick={() => available && setActiveTab(tab.id)}
                className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium whitespace-nowrap transition-all ${
                  activeTab === tab.id
                    ? 'bg-brand-600/20 text-brand-400 border border-brand-500/30'
                    : available
                      ? 'text-gray-400 hover:text-white hover:bg-white/5'
                      : 'text-gray-600 cursor-not-allowed'
                }`}
              >
                <tab.icon className="w-3.5 h-3.5" />
                {tab.label}
              </button>
            );
          })}
        </div>
        {totalTokens > 0 && (
          <div className="text-[10px] text-gray-600 shrink-0 ml-2">
            {totalTokens.toLocaleString()} tokens | ~${estimatedCost.toFixed(3)}
          </div>
        )}
      </div>

      {activeModel && analysis && (
        <div className="flex justify-end">
          <ModelBadge modelId={activeModel} />
        </div>
      )}

      <div className="min-h-[400px]">
        {activeTab === 'intelligence' && analysis && <BusinessIntelligenceTab data={analysis} />}
        {activeTab === 'recommendations' && analysis && <ServiceRecommendationsTab data={analysis} />}
        {activeTab === 'roi' && roi && <ROICalculatorTab data={roi} />}
        {activeTab === 'roi' && !roi && currentStep >= 2 && <TabError label="ROI calculation" />}
        {activeTab === 'outreach' && outreach && <OutreachTab data={outreach} />}
        {activeTab === 'outreach' && !outreach && currentStep >= 3 && <TabError label="Outreach messages" />}
        {activeTab === 'competitor' && competitor && <CompetitorTab data={competitor} />}
        {activeTab === 'competitor' && !competitor && currentStep >= 4 && <TabError label="Competitor analysis" />}
        {activeTab === 'proposal' && proposal && <ProposalTab data={proposal} businessName={businessName} />}
        {activeTab === 'proposal' && !proposal && currentStep >= 5 && <TabError label="Proposal" />}
        {activeTab === 'report' && analysis && <FullReportTab analysis={analysis} roi={roi} proposal={proposal} businessName={businessName} />}

        {!analysis && (
          <div className="flex flex-col items-center justify-center py-20 text-center">
            <div className="w-16 h-16 rounded-2xl bg-dark-700 flex items-center justify-center mb-4">
              <Target className="w-8 h-8 text-gray-500" />
            </div>
            <h3 className="text-lg font-semibold text-gray-300 mb-1">Ready to Analyze</h3>
            <p className="text-sm text-gray-500 max-w-sm">Fill in the business details and click "Analyze with AI" to generate a complete intelligence report.</p>
          </div>
        )}
      </div>
    </div>
  );
}
