/*
  # Create Audit Logs Table

  ## Purpose
  Stores security audit events generated by Edge Functions (team-auth, etc.)
  for compliance monitoring, intrusion detection, and forensic analysis.

  ## New Tables
  - `audit_logs`
    - `id` (uuid, primary key)
    - `event_type` (text) - e.g. "login_success", "login_failure", "password_change"
    - `actor_id` (uuid, nullable) - team_member id who performed the action
    - `actor_email` (text, nullable) - email of the actor
    - `ip_address` (text, nullable) - client IP address
    - `user_agent` (text, nullable) - client user agent string
    - `metadata` (jsonb, nullable) - additional event-specific data
    - `created_at` (timestamptz) - when the event occurred

  ## Security
  - RLS enabled: only the owning user (via team_member owner) can read their own audit logs
  - INSERT restricted to service role only (edge functions use service role key)
  - No UPDATE or DELETE policies (audit logs are immutable)

  ## Indexes
  - idx_audit_logs_actor_id: for querying by actor
  - idx_audit_logs_event_type: for filtering by event type
  - idx_audit_logs_created_at: for time-range queries
*/

CREATE TABLE IF NOT EXISTS audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  actor_id uuid REFERENCES team_members(id) ON DELETE SET NULL,
  actor_email text,
  ip_address text,
  user_agent text,
  metadata jsonb DEFAULT '{}',
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_id ON audit_logs(actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_event_type ON audit_logs(event_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Team members can view their own audit logs"
  ON audit_logs FOR SELECT
  TO authenticated
  USING (
    actor_id IN (
      SELECT id FROM team_members WHERE owner_id = auth.uid()
    )
    OR
    actor_id IN (
      SELECT id FROM team_members WHERE id = actor_id AND owner_id = auth.uid()
    )
  );
